apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook
webhooks:
  - name: pod-labeler.k8s.io
    clientConfig:
      service:
        name: pod-labeler-service
        namespace: default
        path: /mutate
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWc4Q0ZIU0d0Y2swSXd2L1AzakI1S3VhdjAvS0VEeVlNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1GQXgKQ3pBSkJnTlZCQVlUQWtsT01Rc3dDUVlEVlFRSURBSkJVREVMTUFrR0ExVUVCd3dDU0ZreEN6QUpCZ05WQkFvTQpBa0ZDTVFzd0NRWURWUVFMREFKVlFURU5NQXNHQTFVRUF3d0VSRlZVVkRBZUZ3MHlOVEEwTWpjd09UVXpNVEZhCkZ3MHlOVEExTWpjd09UVXpNVEZhTUZBeEN6QUpCZ05WQkFZVEFrbE9NUXN3Q1FZRFZRUUlEQUpCVURFTE1Ba0cKQTFVRUJ3d0NTRmt4Q3pBSkJnTlZCQW9NQWtGQ01Rc3dDUVlEVlFRTERBSlZRVEVOTUFzR0ExVUVBd3dFUkZWVQpWRENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMSHJraU83eVVDc2JUU3lnR3BUClRtZk10VFhncEozY3ZDanIrZ0pxT3B6dm1uclp1RkNnWUY0bW02WVFndzBYOFd3bkg3VktnQ20zRVh2bmY3ejQKSE5aRUhXWTFxdmJLbkpsYWZldkROS1lBZE5PVGpYMGJlZWRZUEgrOE80djU1a2pXbEpCMld2VGhqcGRUMVFnNQpLVGJmRFlMWnZSb0xHRUFGUllJMCt4UFBDNW5ESzJDY1ZLNjBheXF4VSsrWGtRUC8xM0xzc2haQkY3QUJoWVo3CjdjRkVOaGNEc3U2a3IyTVB4UlJHWVd4NU1tUzNQbVk0RStxbkZ1ZW0vSjZJaEZ6dCt0TlQ5bTluYVVwNlBmMEkKWHFLTGNuSkw1TldWczdJT1NmdS9sL1RuMzh6K0RwbW5jZjR1MWEwdTdGLzBRYkRYOFc3cldTZ1dMcHRPK2hzTQpiQnNDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFsajFMRGMrTW1sTjFnRmpDMWJjWG9EWWMyNWtlCmwxU0ZkcjIyOVI2eGd4ZHNTc1AyS3FzdzZORkhiMGZMK0dnYnlMaGNHOXFrclI0eW1SanVXc0ZmSTZHbkE5N2wKenFHSEdjc3FxdThMQlVraXU5N1hyUXNWZm1BdjJOcVhiMnZ3STgya0JiWFc5Q2Urd01uRnNlNXNXeGFRc2MxOAowOWF4ME1nVjhBNzZMeWpRMlpyUFZZNnZrWm5paDdNQnZzVE5yN3FXV1JKSzhHWTUrZzI3ZUUreHA4bXpkWWdjCnBlZ0Z4M0xneUM4blFjek9WOE0yangxYUpldUxWYk9FVklHeitxRTdNYStXdkp1MnZaajFTL0dMVFVkS2lDTFIKcjFlbE9SdXZ4SEFJSzRYTVJjYjRZVjhHKzd5anE5L1Y1TzhrYXdZcGg3YWpyTjJFTy9LOFNiMnVYUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K


    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1"]
    sideEffects: None

